/**
 * Test to verify earnings have all required fields
 */

// Test earnings normalization logic
const testEarningsNormalization = () => {
    const annualCTC = 1200000;
    
    // Test 1: Auto-generated earnings
    console.log('\n=== TEST 1: Auto-generated Earnings ===');
    const monthlyBasic = Number((annualCTC / 12 * 0.5).toFixed(2));
    const monthlyDearness = Number((annualCTC / 12 * 0.3).toFixed(2));
    const monthlyAllowance = Number((annualCTC / 12 * 0.2).toFixed(2));
    
    const autoGenerated = [
        { 
            name: 'Basic', 
            monthlyAmount: monthlyBasic,
            annualAmount: Number((monthlyBasic * 12).toFixed(2)),
            calculationType: 'FIXED',
            percentage: 0,
            proRata: true, 
            taxable: true,
            isRemovable: false,
            enabled: true
        },
        { 
            name: 'Dearness Allowance', 
            monthlyAmount: monthlyDearness,
            annualAmount: Number((monthlyDearness * 12).toFixed(2)),
            calculationType: 'FIXED',
            percentage: 0,
            proRata: true, 
            taxable: true,
            isRemovable: true,
            enabled: true
        },
        { 
            name: 'Allowance', 
            monthlyAmount: monthlyAllowance,
            annualAmount: Number((monthlyAllowance * 12).toFixed(2)),
            calculationType: 'FIXED',
            percentage: 0,
            proRata: false, 
            taxable: true,
            isRemovable: true,
            enabled: true
        }
    ];
    
    console.log('Auto-generated earnings:');
    autoGenerated.forEach((earning, idx) => {
        console.log(`  ${idx + 1}. ${earning.name}`);
        console.log(`     - monthlyAmount: ${earning.monthlyAmount} ✓`);
        console.log(`     - annualAmount: ${earning.annualAmount}`);
        console.log(`     - calculationType: ${earning.calculationType}`);
        console.log(`     - proRata: ${earning.proRata}`);
        console.log(`     - taxable: ${earning.taxable}`);
    });
    
    // Test 2: Earnings mapping logic
    console.log('\n=== TEST 2: Earnings Normalization Mapping ===');
    
    const earningsToNormalize = [
        { name: 'Basic', monthlyAmount: 50000 },
        { name: 'Bonus', monthlyAmount: 10000, taxable: false }
    ];
    
    const normalized = earningsToNormalize.map(earning => {
        if (!earning.name || earning.monthlyAmount === undefined) {
            throw new Error(`Earning component missing required fields: name="${earning.name}", monthlyAmount=${earning.monthlyAmount}`);
        }
        const monthlyAmount = Number(earning.monthlyAmount) || 0;
        const annualAmount = Number((monthlyAmount * 12).toFixed(2));
        return {
            name: String(earning.name).trim(),
            monthlyAmount: monthlyAmount,
            annualAmount: annualAmount,
            calculationType: earning.calculationType || 'FIXED',
            percentage: earning.percentage || 0,
            componentCode: earning.componentCode || '',
            proRata: earning.proRata === true || (earning.proRata === undefined && earning.name.toLowerCase().includes('basic')),
            taxable: earning.taxable !== false,
            isRemovable: earning.isRemovable !== false,
            enabled: earning.enabled !== false
        };
    });
    
    console.log('Normalized earnings:');
    normalized.forEach((earning, idx) => {
        console.log(`  ${idx + 1}. ${earning.name}`);
        console.log(`     - monthlyAmount: ${earning.monthlyAmount} ✓`);
        console.log(`     - annualAmount: ${earning.annualAmount} ✓`);
        console.log(`     - calculationType: ${earning.calculationType} ✓`);
        console.log(`     - proRata: ${earning.proRata}`);
        console.log(`     - taxable: ${earning.taxable}`);
    });
    
    // Test 3: Validation check
    console.log('\n=== TEST 3: Validation Check ===');
    
    let isValid = true;
    [...autoGenerated, ...normalized].forEach((earning, idx) => {
        const hasName = !!earning.name;
        const hasMonthly = earning.monthlyAmount !== undefined;
        const hasAnnual = earning.annualAmount !== undefined;
        const hasCalcType = !!earning.calculationType;
        
        if (!hasName || !hasMonthly || !hasAnnual || !hasCalcType) {
            console.log(`  ✗ Earning ${idx} FAILED validation`);
            isValid = false;
        }
    });
    
    if (isValid) {
        console.log('  ✓ ALL EARNINGS HAVE REQUIRED FIELDS');
        console.log('  ✓ name: Present in all earnings');
        console.log('  ✓ monthlyAmount: Present in all earnings');
        console.log('  ✓ annualAmount: Present in all earnings');
        console.log('  ✓ calculationType: Present in all earnings');
    }
    
    console.log('\n=== RESULT: READY FOR PRODUCTION ===\n');
};

testEarningsNormalization();
